swagger: '2.0'

info:
  version: '1.0.0'
  title: 'Users'
  description: 'Microservice for managing users.'
  contact:
    name: Jarrod Parkes
    email: jarrod@udacity.com
    url: http://jarrodparkes.com
  license:
    name: MIT License

schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /login:
    post:
      description: Login user and generate base64 encoded JWT.
      summary: Login user and generate base64 encoded JWT.
      parameters:
       - name: code
         in: query
         description: Facebook authorization code.
         type: string
         pattern: '^(\w{280})$'
      responses:
        200:
          description: Login successful.
          schema:
            $ref: '#/definitions/Access'
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/Message'
  /logout:
    get:
      description: Logout user and invalidate the provided JWT.
      summary: Logout user and invalidate the provided JWT.
      responses:
        200:
          description: Logout successful.
          schema:
            $ref: '#/definitions/Message'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Message'
      security:
      - user_auth: []
  /profile:
    get:
      description: Retrieve the current user's profile.
      summary: Retrieve the current user's profile.
      responses:
        200:
          description: Successful response.
          schema:
            $ref: '#/definitions/Profile'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Message'
      security:
      - user_auth: []
    put:
      description: Update the current user's profile.
      summary: Update the current user's profile.
      parameters:
        - name: profile
          in: body
          description: Data to update current user.
          required: true
          schema:
            $ref: '#/definitions/UpdateProfile'
      responses:
        200:
          description: Successful response.
          schema:
            $ref: '#/definitions/Message'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Message'     
  /favorites:
    put:
      description: Add or remove favorites from current user's profile.
      summary: Add or remove favorites from current user's profile.
      parameters:
        - in: body
          name: favorites
          description: Activities to add or remove from favorites.
          required: true
          schema:
            $ref: '#/definitions/UpdateFavorite'
      responses:
        200:
          description: Successful response.
          schema:
            $ref: '#/definitions/Message'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Message'
      security:
      - user_auth: []

responses:
  NoContent:
    description: The request was fulfilled, but nothing to return.
  BadRequest:
    description: Invalid request.
  NotModified:
    description: The specified resource was not modified.
  NotFound:
    description: The specified resource was not found.
  Unauthorized:
    description: Unauthorized.

securityDefinitions:
  user_auth:
    type: apiKey
    description: Base64 encoded JWT
    name: Authorisation bearer
    in: header

definitions:
  Profile:
    allOf:
      - $ref: '#/definitions/UpdateProfile'
      - required:
        - id
        - created_at
        - updated_at
        properties:
          id:
            type: string
            description: ID of user.
            readOnly: true
            default: "1"
          created_at:
            type: string
            description: Date event was created.
            format: YYYY-mm-dd HH:mm:ss
            default: "2017-07-24 20:43:51"
          updated_at:
            type: string
            description: Date event was created.
            format: YYYY-mm-dd HH:mm:ss
            default: "2017-07-24 20:43:51"
  UpdateProfile:
    type: object
    properties:
      name:
        type: string
        description: User's full name.
        default: "Julian Doe"
      photo_url:
        type: string
        description: URL to user's profile image.
        default: "https://example.net"
      location:
        type: string
        description: User's location.
        default: "San Francisco, CA"
    required:
      - name
      - photo_url
      - location
  UpdateFavorite:
    type: object
    properties:
      activity_ids:
        type: array
        items:
          type: string
          description: ID of activity.
          default: "4"
      favorite:
        type: boolean
        description: If true, add to favorites. If false, remove from favorites.
        default: true
    required:
      - activity_ids
      - favorite
  Message:
    type: object
    properties:
      message:
        type: string
        description: A message.
    required:
      - message
    example:
      message: "A message describing the HTTP status code."
  Access:
    type: object
    properties:
      id:
        type: string
        description: User id.
        pattern: '^(\d{15})$'
      jwt:
        type: string
        description: A base64 encoded JWT.
        pattern: '^(\w{100})$'
    required:
      - id
      - token