swagger: '2.0'

info:
  version: '1.0.0'
  title: 'Users'
  description: 'Microservice for managing users.'
  contact:
    name: Jarrod Parkes
    email: jarrod@udacity.com
    url: http://jarrodparkes.com
  license:
    name: MIT License

schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /user/login:
    post:
      consumes:
      - application/json
      produces:
      - text/plain
      description: This endpoint allows the user to authenticate with the system by passing a valid Facebook authorisation token.
      parameters:
      - name: token
        in: body
        required: true
        schema:
          type: object
          properties:
            token:
              type: string
      responses:
        '200':
          description: Login successful - returns a Base64 encoded JWT.
          schema:
            type: string
        '401':
          description: Not authorised
  /user/logout:
    get:
      description: Log the current user out of the system and invalidate the provided JWT.
      responses:
        '200':
          description: Logout successful.
        '401':
          description: Not authorised.
      security:
      - user_auth: []
  /user/profile:
    get:
      description: Retrieve the current user's profile.
      produces:
      - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Profile'
        '401':
          description: Not authorised
      security:
      - user_auth: []
  /user/favorite:
    post:
      description: Add favorite to user's profile.
      parameters:
        - in: body
          name: favorite
          description: Activity to favorite.
          schema:
            type: object
            required:
              - favorite_id
            properties:
              favorite_id:
                type: string
                default: "2"
              favorite:
                type: boolean
                default: true
              unfavorite:
                type: boolean
                default: false
      produces:
      - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Status'
        '401':
          description: Not authorised
      security:
      - user_auth: []
securityDefinitions:
  user_auth:
    type: apiKey
    description: Base64 encoded JWT
    name: Authorisation bearer
    in: header
definitions:
  Profile:
    allOf:
      - $ref: '#/definitions/NewProfile'
      - required:
        - id
        properties:
          id:
            type: string
            description: ID of user.
            readOnly: true
            default: "1"
  NewProfile:
    type: object
    properties:
      name:
        type: string
        description: User's full name.
        default: "Julian Doe"
      photo_url:
        type: string
        description: URL to user's profile image.
        default: "https://example.net"
      location:
        type: string
        description: User's location.
        default: "San Francisco, CA"
      created_at:
        type: string
        description: Date event was created.
        format: YYYY-mm-dd HH:mm:ss
        default: "2017-07-24 20:43:51"
      updated_at:
        type: string
        description: Date event was created.
        format: YYYY-mm-dd HH:mm:ss
        default: "2017-07-24 20:43:51"
  Status:
    type: object
    properties:
      code:
        type: integer
        description: Error status code.
        format: int32
        default: 1
      message:
        type: string
        description: Error description.
        default: "Activity favorited."
    required:
      - code
      - message